Create maintenance page vue
ProjectPGA/Portfolio-Platform-Frontend pull request #11
Opened 2021-02-02 20:29 UTC by gonzalo-plaza

2021-02-03 14:17 UTC, gonzalo-plaza commented
@Andresws12 I have change the styles appling the code review of @JuanJosePG , but I need do the colors palette branch befor of apply the variables in maintenance page vue.

2021-02-03 14:48 UTC, Andresws12 requested changes

2021-02-03 14:48 UTC, Andresws12 commented on src/views/Maintenancepage.vue
> +export default class Maintenance extends Vue {
@gonzalo-plaza There are two problems jejeje on the one hand, you are calling this component Maintenancepage.vue and all components are calling in UpperCamelCase, so this component should called MaintenancePage.vue, on the other hand, if this component is calling MaintenancePage why you declare the class Maintenance? and the name from the component Maintenance? The name from the component and the name should be same that the name from the file

2021-02-03 14:48 UTC, Andresws12 commented on src/views/Maintenancepage.vue
> +                src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGlkPSJPQkpFQ1RTIiB2aWV3Qm94PSIwIDAgMzg4Ljk2IDMzMS41MiI+CiAgPGRlZnMvPgogIDxkZWZzPgogICAgPHN0eWxlPgog
@gonzalo-plaza Now we can add this image on assets/img, the base 64 is only to static page, please add this iamge in this dir and use this image

2021-02-03 14:48 UTC, Andresws12 commented on src/views/Maintenancepage.vue
> +        <div class="maintenance-page_content level is-mobile">
@gonzalo-plaza Why are you using level and is-mobile, if you cadd add this styles using the class _content  and is not showing correctly on my laptop, please review in others desktop views
![image](https://user-images.githubusercontent.com/47737142/106762624-4b264b00-6636-11eb-9f56-b8be6e79b65f.png)

2021-02-03 14:48 UTC, Andresws12 commented on src/views/Maintenancepage.vue
> +import mainStore from '@/store/main-store/MainStore';
@gonzalo-plaza Why are you calling the store? and on the code, you declare the store, and declare currentLanguaje, but... where are you using currentLanguaje? this get method onli return es or en, if the language is english or spanish, but you need change this languaje,  for this, we have a generic component called 'ButtonTranslation' on login dir from appointment system, maybe you cand copy and paste this component in common dir, and use this component like is using in login view from appointments

To use this component you can see how we use this componennt on MainLoginForm componentthere are a component

2021-02-03 14:48 UTC, Andresws12 commented on src/views/Maintenancepage.vue
> +@media (max-width: 750px) {
@gonzalo-plaza We have tree diferents mixins to use this media, you can use touch, mobile and desktop, like that Jose is using in appoinment maintenance page

2021-02-04 18:52 UTC, Andresws12 requested changes

2021-02-04 18:52 UTC, Andresws12 commented on src/views/MaintenancePage.vue
> +                src="../assets/img/mantenimiento-image.svg"
@gonzalo-plaza English please

2021-02-04 18:52 UTC, Andresws12 commented on src/views/MaintenancePage.vue
> +                <div class="maintenance-page_title">
@gonzalo-plaza It's a good practice use h1 to titles and h2 to subtitles, cause the SEO works veri good with h1 and h2, in maintenance is not importatn but.... if good use this

2021-02-04 18:52 UTC, Andresws12 commented on src/views/MaintenancePage.vue
> +    <main class="maintenance-page">
@gonzalo-plaza this component is not the main from the page, cause the main is app.vue, maybe is confusing if we add main on the views or components, cause the main represent the main content from the app, and this content is a one part from this,.

2021-02-04 18:52 UTC, Andresws12 commented on src/views/MaintenancePage.vue
> +import { Component, Vue } from 'vue-property-decorator';
@gonzalo-plaza please add a white line to separe the imports, cause theese are diferents imports, on the one hand, we import a library and on the other hand we are importing the components and also add withe line space, to separe the imports component that '@components'

2021-02-05 14:09 UTC, gonzalo-plaza commented
@Andresws12 This code can be review.

2021-02-08 14:34 UTC, Andresws12 commented
@gonzalo-plaza On my laptop the image is so big 
![image](https://user-images.githubusercontent.com/47737142/107233622-1265e780-6a23-11eb-9461-e7a9854ff19e.png)

2021-02-08 14:41 UTC, gonzalo-plaza commented
@Andresws12 Ok!! Y review more posibilitys to apply the responsive

2021-02-08 20:32 UTC, merged